services:
  fastapi:
    image: python:3.8-slim
    ports:
      - "8000:80"
    volumes:
      - ./fastapi:/app
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 80
    command: >
      sh -c "pip install -r requirements.txt &&
            uvicorn main:app --host 0.0.0.0 --port 80"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - './mongodb_data:/data/db'
      - './mongodb_config:/data/configdb'

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_INITDB_ROOT_URL}
    depends_on:
      - mongo